# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
              sudo apt install aapt apksigner -y
              ./update.sh && ./build.sh all
              ls ./releases              


      # Upload Artifact
      - name: Upload production-ready releases files
        uses: actions/upload-artifact@v3
        with:
          name: production
          path: ./releases

      - name: Upload generated file as release asset
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          build_repo: ${{ github.repository }}
          file: ./releases
          token: ${{ secrets.GITHUB_TOKEN }}
          repo_token: ${{ secrets.Forked_REPO_TOKEN }}
              



